### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by cronfy** [uranum/yii2-delivery-calculator#5]
Здравствуйте.

Какая лицензия у вашего проекта? Можно ли использовать код в коммерческих целях?

**Comment by ev-emelyanov** [comment]
Добрый день

Никакой лицензии нет, проект личный, но если выложен в свободный доступ - можете использовать.

**Comment by cronfy** [comment]
Я вижу, у вас в composer.json указано BSD-3-Clause, Вы не могли бы тогда добавить в корень репозитория файлик LICENSE с этой лицензией, чтобы были понятны условия заимствования проекта? Спасибо!
