### ISSUE TITLE
Поддержка PostgreSQl

### ISSUE THREAD

**Issue by Ioprst** [uranum/yii2-delivery-calculator#7]
Привет. Запускаю миграции и получаю следующие ошибки.
БД PostgreSQL 9.5 -x64

http://joxi.ru/J2bY1bqSXvJevm

**Comment by uranum** [comment]
Перепишите под postgre [эту строку](https://github.com/uranum/yii2-delivery-calculator/blob/13fbaaab8922909887ecb4d3b10bf30763b654ea/migration/m170323_074600_TableDeliveries.php#L27), я обновлю

**Comment by Ioprst** [comment]
'isActive' => $this->boolean()->notNull()->defaultValue(true)->comment('Активно'),  - поменял 1 на true
'dateDb' => $this->dateTime()->defaultExpression('NOW()') - on update Postgres не поддерживает.

**Comment by Ioprst** [comment]
проверил на Mysql 5.6 и PostgreSQL 9.5 -x64
